config/routes.rb
Rails.application.routes.draw do 

  resources :exercicios, :path => "exercicios" do
    collection do
      get "/pesquisaexercicio"  => "exercicios#pesquisaexercicio", :as => "pesquisaexercicio"
    end
  end    
  resources :treinos, :path =>  "treinos" do 
    collection do
      get "/exercicio/:idexe/:tam" => "treinos#exercicio", :as => "exercicio"
    end
  end
  root "users#sign_in"
  devise_for :users , controllers: {
      registrations: "users/registrations",
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get 'signup', to: 'users/registrations#new'
    get 'signin', to: 'users/sessions#new'
    get 'signout', to: 'users/registrations#destroy'
  end
  resources :users, :path => "users" do
    collection do
      post "/createuser" => "users#createuser", :as => "createuser"      
          
    end
  end
  resources :saidas
  resources :entradas, :path => "entradas" do
    collection do

      get "/showpdf"  => "entradas#showpdf", :as => "showpdf"

    end
  end  
  resources :planos
  resources :modalidades
  resources :fornecedors
  resources :clientes

  get "caixa/index" => "caixa/index" , :as => "caixa/index"

  #get "treinos/exercicio/:idexc/:tam", to: "treinos#exercicio"

  get "treinos/exercicio/:id/:idcliente/:idplano/:exercicio_id", to: "treinos#exercicio"

  get "entradas/buscarvalorplano/:idplano"  => "entradas#buscarvalorplano", :as => "buscarvalorplano"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user != nil and user.tipo=='Admin'
         can :manage, :all
       elsif user != nil and user.tipo=='Funcionário'         
         can [:read,:create], Entrada
         can [:read,:create], Saida            
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano
  belongs_to :modalidade
end

app/models/exercicio.rb
class Exercicio < ApplicationRecord
end

app/models/exrciciotreino.rb
class Exrciciotreino < ApplicationRecord
  belongs_to :treino
  belongs_to :exercicio
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
end

app/models/plano.rb
class Plano < ApplicationRecord
end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :modalidade
end

app/models/treino.rb
class Treino < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano

	has_many :exrciciotreinos, inverse_of: :treino, dependent: :destroy
	accepts_nested_attributes_for :exrciciotreinos, reject_if: :all_blank, allow_destroy: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/saidas_controller.rb
class SaidasController < ApplicationController
  before_action :set_saida, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /saidas
  # GET /saidas.json
  def index
    @saidas = Saida.all
  end

  # GET /saidas/1
  # GET /saidas/1.json
  def show
  end

  # GET /saidas/new
  def new
    @saida = Saida.new
  end

  # GET /saidas/1/edit
  def edit
  end

  # POST /saidas
  # POST /saidas.json
  def create
    @saida = Saida.new(saida_params)

    respond_to do |format|
      if @saida.save
        format.html { redirect_to @saida, notice: 'Saida was successfully created.' }
        format.json { render :show, status: :created, location: @saida }
      else
        format.html { render :new }
        format.json { render json: @saida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saidas/1
  # PATCH/PUT /saidas/1.json
  def update
    respond_to do |format|
      if @saida.update(saida_params)
        format.html { redirect_to @saida, notice: 'Saida was successfully updated.' }
        format.json { render :show, status: :ok, location: @saida }
      else
        format.html { render :edit }
        format.json { render json: @saida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saidas/1
  # DELETE /saidas/1.json
  def destroy
    @saida.destroy
    respond_to do |format|
      format.html { redirect_to saidas_url, notice: 'Saida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saida
      @saida = Saida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saida_params
      params.require(:saida).permit(:fornecedor_id, :modalidade_id, :descricao, :valor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caixa_helper.rb
module CaixaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/planos_helper.rb
module PlanosHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/helpers/treinos_helper.rb
module TreinosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/saidas/_form.html.erb
<%= form_with(model: saida, url: createuser_users_path, local: true) do |form| %>
  <% if saida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saida.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% saida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-10 form-group">
  
  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :fornecedor_id, :class => 'control-label' %>
    <%= form.collection_select :fornecedor_id, Fornecedor.order(:nome) , :id, :nome, {:prompt => 'Selecionar'}, :class => 'form-control', :id => 'saida_fornecedor_id' %>
  </div>
  </div>

   <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :modalidade_id, :class => 'control-label' %>
    <%= form.collection_select :modalidade_id, Modalidade.order(:nome) , :id, :nome, {:prompt => 'Selecionar'}, :class => 'form-control', :id => 'saida_modalidade_id' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :descricao,"Descrição", :class => 'control-label' %>
    <%= form.text_field :descricao, id: :saida_descricao, :class => 'form-control' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-2 form-group">
    <%= form.label :valor,'Valor Total', :class => 'control-label' %>
    <%= form.number_field :valor, id: :saida_valor, :class => 'form-control' %>       
  </div>
  </div>

  <div class="row">
  <div class="col-lg-7 form-group">  
      <input type="submit" name="commit" class="btn btn-primary" value="Salvar" data-disable-with="Salvar" />
      <%= link_to 'Voltar', saidas_path, :class => "btn btn-primary"%>
  </div>
  </div>

  </div>

<% end %>

app/views/saidas/edit.html.erb
<h1>Editar Saida</h1>

<%= render 'form', saida: @saida %>

app/views/saidas/index.html.erb
<div class="categdespesas index">
      <h2>Saidas </h2>
       <%= form_tag saidas_path( format:"html"), :method => 'get' do %>  
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
          <div class="col-lg-4  form-group">  
            <%= text_field_tag :nome, params[:nome], :class => 'form-control', :placeholder=>"Nome do Fornecedor" %>  
          </div>
          <div class="col-lg-4 form-group">
                <%= submit_tag "Pesquisar", :class => "btn btn-primary" %>
          </div>

                  
        <div class="col-lg-2 form-group">  
          <span class="input-group-btn" style="display: inline-block;"><button class="btn btn-primary" type="button" onclick="javascript: location.href='<%= new_saida_path %>';"><i class="fa fa-plus-circle"></i> Nova Saída</button></span>
        </div>
        </div>
      </div>
      </div>
      <% end  %>  
      
  <div class="table-responsive">
  <table class="table table-hover table-striped" cellpadding="0" cellspacing="0">
      <thead>
      <tr>
      <th>Código</th>
      <th>Data</th>
      <th>Fornecedor</th>
      <th>Modalidade</th>
      <th>Descricao</th>
      <th>Valor</th>    
      <th colspan="3"></th>
                      
      </thead>
      <tbody>
    <% @saidas.each do |saida| %>
      <tr>
        <td><%= saida.id %></td>
        <td><%= saida.created_at.strftime("%d/%m/%Y ") %></td>
        <td><%= saida.fornecedor.nome %></td>
        <td><%= saida.modalidade.nome %></td>
        <td><%= saida.descricao %></td>
        <td><%= saida.valor %></td>        
        <td><%= link_to 'Exibir', saida %></td>
        <td><%= link_to 'Editar', edit_saida_path(saida) %></td>
        <td><%= link_to 'Deletar', saida, method: :delete, data: { confirm: 'Deseja Deletar '+saida.fornecedor.nome+'?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>


  </div>

app/views/saidas/new.html.erb
<h1>Nova Saída</h1>

<%= render 'form', saida: @saida %>

app/views/saidas/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="page-header">
                Visualizar Saída
            </h2>
        </div>
    </div>
    <div class="curso form">

           <div class="row">

               <div class="col-lg-4 form-group">   
                  <label class = 'control-label'>Fornecedor</label>
                  <input readonly="true" class = 'form-control' value="<%= @saida.fornecedor.nome %>" />
               </div>

           </div>    

           <div class="row">
                <div class="col-lg-4 form-group">   
                  <label class = 'control-label'>Modalidade</label>
                  <input readonly="true" class = 'form-control' value="<%= @saida.modalidade.nome %>" />
                </div>
           </div>

           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Descrição</label>
                  <input readonly="true" class = 'form-control' value="<%= @saida.descricao %>" />
                </div>
           </div>
                
           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Valor</label>
                  <input readonly="true" class = 'form-control' value="<%= @saida.valor %>" />
                </div>
           </div>             
            
             <div class="row">
                <div class="col-lg-4 form-group">  
                  <%= link_to 'Editar', edit_saida_path(@saida), :class => "btn btn-primary" %>
                  <%= link_to 'Voltar', saidas_path, :class => "btn btn-primary"%>
                </div>
            </div>
     
                          
    </div>
</div>