config/routes.rb
Rails.application.routes.draw do 

  resources :exercicios, :path => "exercicios" do
    collection do
      get "/pesquisaexercicio"  => "exercicios#pesquisaexercicio", :as => "pesquisaexercicio"
    end
  end    
  resources :treinos, :path =>  "treinos" do 
    collection do
      get "/exercicio/:idexe/:tam" => "treinos#exercicio", :as => "exercicio"
    end
  end
  root "users#sign_in"
  devise_for :users , controllers: {
      registrations: "users/registrations",
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get 'signup', to: 'users/registrations#new'
    get 'signin', to: 'users/sessions#new'
    get 'signout', to: 'users/registrations#destroy'
  end
  resources :users, :path => "users" do
    collection do
      post "/createuser" => "users#createuser", :as => "createuser"      
          
    end
  end
  resources :saidas
  resources :entradas, :path => "entradas" do
    collection do

      get "/showpdf"  => "entradas#showpdf", :as => "showpdf"

    end
  end  
  resources :planos
  resources :modalidades
  resources :fornecedors
  resources :clientes

  get "caixa/index" => "caixa/index" , :as => "caixa/index"

  #get "treinos/exercicio/:idexc/:tam", to: "treinos#exercicio"

  get "treinos/exercicio/:id/:idcliente/:idplano/:exercicio_id", to: "treinos#exercicio"

  get "entradas/buscarvalorplano/:idplano"  => "entradas#buscarvalorplano", :as => "buscarvalorplano"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user != nil and user.tipo=='Admin'
         can :manage, :all
       elsif user != nil and user.tipo=='Funcionário'         
         can [:read,:create], Entrada
         can [:read,:create], Saida            
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano
  belongs_to :modalidade
end

app/models/exercicio.rb
class Exercicio < ApplicationRecord
end

app/models/exrciciotreino.rb
class Exrciciotreino < ApplicationRecord
  belongs_to :treino
  belongs_to :exercicio
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
end

app/models/plano.rb
class Plano < ApplicationRecord
end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :modalidade
end

app/models/treino.rb
class Treino < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano

	has_many :exrciciotreinos, inverse_of: :treino, dependent: :destroy
	accepts_nested_attributes_for :exrciciotreinos, reject_if: :all_blank, allow_destroy: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

    def buscarvalorplano

    @valor = Plano.select("planos.valor as valor").where("planos.id="+params[:idplano])

    respond_to do |format|
        format.json { render json: @valor }
      end

  end

  # GET /entradas/1/edit
  def edit
  end

  def showpdf            

    @entradas = Entrada.all
    respond_to do |format|
      format.html
      format.pdf do
        pdf = EntradaPdf.new(@entradas, view_context)
        send_data pdf.render,
          filename: 'Entrada.pdf',
          type: 'application/pdf',
          disposition: 'inline'
      end
  end
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada was successfully created.' }
        format.json { render :show, status: :created, location: @entrada }
      else
        format.html { render :new }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrada }
      else
        format.html { render :edit }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url, notice: 'Entrada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:cliente_id, :plano_id, :modalidade_id, :descricao, :valor, :desconto, :total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caixa_helper.rb
module CaixaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/planos_helper.rb
module PlanosHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/helpers/treinos_helper.rb
module TreinosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entradas/_form.html.erb
<%= form_with(model: entrada, local: true) do |form| %>
  <% if entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entrada.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% entrada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-10 form-group">
  
  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :cliente_id, :class => 'control-label' %>
    <%= form.collection_select :cliente_id, Cliente.order(:nome) , :id, :nome, {:prompt => 'Selecionar'}, :class => 'form-control', :id => 'entrada_cliente_id' %>
  </div>
  </div>

   <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :plano_id, :class => 'control-label' %>
    <%= form.collection_select :plano_id, Plano.order(:nome) , :id, :nome, {:prompt => 'Selecionar'}, :class => 'form-control', :id => 'entrada_plano_id' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :modalidade, :class => 'control-label' %>    
    <%= form.collection_select :modalidade_id, Modalidade.order(:nome) , :id, :nome, {:prompt => 'Selecionar'}, :class => 'form-control', :id => 'entrada_modalidade_id' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :descricao,"Descrição", :class => 'control-label' %>
    <%= form.text_field :descricao, id: :entrada_descricao, :class => 'form-control' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-2 form-group">
    <%= form.label :valor, :class => 'control-label' %>
    <%= form.number_field :valor, id: :entrada_valor, :class => 'form-control', :readonly =>'true'%>       
  </div>
  </div>

  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :desconto, :class => 'control-label' %>
    <%= form.number_field :desconto, id: :entrada_desconto, :class => 'form-control' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-2 form-group">
    <%= form.label :total, :class => 'control-label' %>
    <%= form.number_field :total, id: :entrada_total, :class => 'form-control', :readonly =>'true' %>       
  </div>
  </div>


  <div class="row">
  <div class="col-lg-7 form-group">  
      <input type="submit" name="commit" class="btn btn-primary" value="Salvar" data-disable-with="Salvar" />
      <%= link_to 'Voltar', entradas_path, :class => "btn btn-primary"%>
  </div>
  </div>

  </div>

<% end %>

<script type="text/javascript">
   
   

   //Calculando o valor total
   $( "#entrada_desconto" ).keyup(function() {
       var valor = $("#entrada_valor").val();
       var desconto = $("#entrada_desconto").val();
       var total = parseFloat(valor) - parseFloat(desconto);

       if(total > 0){
          document.getElementById('entrada_total').value = total;
       }else{
          alert("Desconto estrapolou o valor total!");
       }
       
   });

 
   //SETANDO O VALOR DO PLANO ESCOLHIDO
      $(document).ready(function(){ 

      $(document).on("change", "#entrada_plano_id", function(){

        var idplano = document.getElementById("entrada_plano_id");

        var valor_selecionado_plano = idplano.options[idplano.selectedIndex].value;
 
         $.ajax({
         remote: true,
         dataType:'json',
         type:'get',
         url: '/entradas/buscarvalorplano/'+ valor_selecionado_plano,
         
         cache: true,
         processData: true,
         success: function(data){

              document.getElementById('entrada_valor').value = data[0].valor;        

         }

         });

       });
      });

 
</script>

app/views/entradas/edit.html.erb
<h1>Editar Entrada</h1>

<%= render 'form', entrada: @entrada %>

app/views/entradas/index.html.erb
 <div class="categdespesas index">
      <h2>Entradas </h2>
       <%= form_tag entradas_path( format:"html"), :method => 'get' do %>  
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
          <div class="col-lg-4  form-group">  
            <%= text_field_tag :nome, params[:nome], :class => 'form-control', :placeholder=>"Nome do Cliente" %>  
          </div>
          <div class="col-lg-4 form-group">
                <%= submit_tag "Pesquisar", :class => "btn btn-primary" %>
          </div>

                  
        <div class="col-lg-2 form-group">  
          <span class="input-group-btn" style="display: inline-block;"><button class="btn btn-primary" type="button" onclick="javascript: location.href='<%= new_entrada_path %>';"><i class="fa fa-plus-circle"></i> Nova Entrada</button></span>
        </div>
        </div>
      </div>
      </div>
      <% end  %>  
      
  <div class="table-responsive">
  <table class="table table-hover table-striped" cellpadding="0" cellspacing="0">
      <thead>
      <tr>
      <th>Codigo</th>
      <th>Data</th>
      <th>Cliente</th>
      <th>Plano</th>
      <th>Modalidade</th>
      <th>Valor</th>
      <th>Desconto</th>
      <th>Total</th>
           
      <th colspan="3"></th>
                      
      </thead>
      <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.id %></td>
        <td><%= entrada.created_at.strftime("%d/%m/%Y ") %></td>
        <td><%= entrada.cliente.nome %></td>
        <td><%= entrada.plano.nome %></td>
        <td><%= entrada.modalidade.nome %></td>
        <td><%= entrada.valor %></td>
        <td><%= entrada.desconto %></td>
        <td><%= entrada.total %></td>
             
        <td><%= link_to 'Exibir', entrada %></td>
        <td><%= link_to 'Editar', edit_entrada_path(entrada) %></td>
        <td><%= link_to 'Deletar', entrada, method: :delete, data: { confirm: 'Deseja Deletar '+entrada.cliente.nome+'?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>


  </div>

app/views/entradas/new.html.erb
<h1>Nova Entrada</h1>

<%= render 'form', entrada: @entrada %>

app/views/entradas/relatorio_entradas.html.erb
 <div class="categdespesas index">
      <h2>Entradas </h2>
       <%= form_tag relatorio_entradas_path( format:"html"), :method => 'get' do %>  
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
          <div class="col-lg-4  form-group">  
            <%= text_field_tag :nome, params[:nome], :class => 'form-control', :placeholder=>"Nome do Cliente" %>  
          </div>
          <div class="col-lg-4 form-group">
                <%= submit_tag "Pesquisar", :class => "btn btn-primary" %>
          </div>

                  
        <div class="col-lg-2 form-group">
                <span class="input-group-btn" style="display: inline-block; 
                padding-left: 7px;">
                <button class="btn btn-primary" type="button" target="_blank" 
                onclick="javascript: location.href='<%= showpdf_entradas_url(format: "pdf") %>';">

                <i class="fa fa-file-text-o" ></i>
                PDF Geral</button>
                
              </span> 

           </div>

        </div>
      </div>
      </div>
      <% end  %>  
      
  <div class="table-responsive">
  <table class="table table-hover table-striped" cellpadding="0" cellspacing="0">
      <thead>
      <tr>
      <th>Codigo</th>
      <th>Data</th>
      <th>Cliente</th>
      <th>Plano</th>
      <th>Modalidade</th>
      <th>Valor</th>
      <th>Desconto</th>
      <th>Total</th>
           
      <th colspan="3"></th>
                      
      </thead>
      <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.id %></td>
        <td><%= entrada.created_at.strftime("%d/%m/%Y ") %></td>
        <td><%= entrada.cliente.nome %></td>
        <td><%= entrada.plano.nome %></td>
        <td><%= entrada.modalidade.nome %></td>
        <td><%= entrada.valor %></td>
        <td><%= entrada.desconto %></td>
        <td><%= entrada.total %></td>
             
        <td><%= link_to 'Exibir', entrada %></td>
        <td><%= link_to 'Editar', edit_entrada_path(entrada) %></td>
        <td><%= link_to 'Deletar', entrada, method: :delete, data: { confirm: 'Deseja Deletar '+entrada.cliente.nome+'?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>


  </div>

app/views/entradas/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="page-header">
                Visualizar Entrada
            </h2>
        </div>
    </div>
    <div class="curso form">

           <div class="row">

               <div class="col-lg-4 form-group">   
                  <label class = 'control-label'>Cliente</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.cliente.nome %>" />
               </div>

           </div>  

           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Plano</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.plano.nome %>" />
                </div>
           </div>  

           <div class="row">
                <div class="col-lg-4 form-group">   
                  <label class = 'control-label'>Modalidade</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.modalidade.nome %>" />
                </div>
           </div>

           <div class="row">
                <div class="col-lg-4 form-group">  
                  <label class = 'control-label'>Descrição</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.descricao %>" />
                </div>
           </div>

           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Valor</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.valor %>" />
                </div>
           </div>

           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Desconto</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.desconto %>" />
                </div>
           </div>
                
           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Total</label>
                  <input readonly="true" class = 'form-control' value="<%= @entrada.total %>" />
                </div>
           </div> 
            
             <div class="row">
                <div class="col-lg-4 form-group">  
                  <%= link_to 'Editar', edit_entrada_path(@entrada), :class => "btn btn-primary" %>
                  <%= link_to 'Voltar', entradas_path, :class => "btn btn-primary"%>
                </div>
            </div>
     
                          
    </div>
</div>