config/routes.rb
Rails.application.routes.draw do 

  resources :exercicios, :path => "exercicios" do
    collection do
      get "/pesquisaexercicio"  => "exercicios#pesquisaexercicio", :as => "pesquisaexercicio"
    end
  end    
  resources :treinos, :path =>  "treinos" do 
    collection do
      get "/exercicio/:idexe/:tam" => "treinos#exercicio", :as => "exercicio"
    end
  end
  root "users#sign_in"
  devise_for :users , controllers: {
      registrations: "users/registrations",
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get 'signup', to: 'users/registrations#new'
    get 'signin', to: 'users/sessions#new'
    get 'signout', to: 'users/registrations#destroy'
  end
  resources :users, :path => "users" do
    collection do
      post "/createuser" => "users#createuser", :as => "createuser"      
          
    end
  end
  resources :saidas
  resources :entradas, :path => "entradas" do
    collection do

      get "/showpdf"  => "entradas#showpdf", :as => "showpdf"

    end
  end  
  resources :planos
  resources :modalidades
  resources :fornecedors
  resources :clientes

  get "caixa/index" => "caixa/index" , :as => "caixa/index"

  #get "treinos/exercicio/:idexc/:tam", to: "treinos#exercicio"

  get "treinos/exercicio/:id/:idcliente/:idplano/:exercicio_id", to: "treinos#exercicio"

  get "entradas/buscarvalorplano/:idplano"  => "entradas#buscarvalorplano", :as => "buscarvalorplano"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user != nil and user.tipo=='Admin'
         can :manage, :all
       elsif user != nil and user.tipo=='Funcionário'         
         can [:read,:create], Entrada
         can [:read,:create], Saida            
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano
  belongs_to :modalidade
end

app/models/exercicio.rb
class Exercicio < ApplicationRecord
end

app/models/exrciciotreino.rb
class Exrciciotreino < ApplicationRecord
  belongs_to :treino
  belongs_to :exercicio
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
end

app/models/plano.rb
class Plano < ApplicationRecord
end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :modalidade
end

app/models/treino.rb
class Treino < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano

	has_many :exrciciotreinos, inverse_of: :treino, dependent: :destroy
	accepts_nested_attributes_for :exrciciotreinos, reject_if: :all_blank, allow_destroy: true	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  before_action :set_modalidade, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /modalidades
  # GET /modalidades.json
  def index
    @modalidades = Modalidade.all
  end

  # GET /modalidades/1
  # GET /modalidades/1.json
  def show
  end

  # GET /modalidades/new
  def new
    @modalidade = Modalidade.new
  end

  # GET /modalidades/1/edit
  def edit
  end

  # POST /modalidades
  # POST /modalidades.json
  def create
    @modalidade = Modalidade.new(modalidade_params)

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully created.' }
        format.json { render :show, status: :created, location: @modalidade }
      else
        format.html { render :new }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalidades/1
  # PATCH/PUT /modalidades/1.json
  def update
    respond_to do |format|
      if @modalidade.update(modalidade_params)
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @modalidade }
      else
        format.html { render :edit }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalidades/1
  # DELETE /modalidades/1.json
  def destroy
    @modalidade.destroy
    respond_to do |format|
      format.html { redirect_to modalidades_url, notice: 'Modalidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modalidade
      @modalidade = Modalidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modalidade_params
      params.require(:modalidade).permit(:nome, :descricao, :receita, :despesa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caixa_helper.rb
module CaixaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/helpers/planos_helper.rb
module PlanosHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/helpers/treinos_helper.rb
module TreinosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/modalidades/_form.html.erb
<%= form_with(model: modalidade, local: true) do |form| %>
  <% if modalidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h2>

      <ul>
      <% modalidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-10 form-group">
  
  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :nome, :class => 'control-label' %>
    <%= form.text_field :nome, id: :modalidade_nome, :class => 'form-control' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-5 form-group">
    <%= form.label :descricao, :class => 'control-label' %>
    <%= form.text_field :descricao, id: :modalidade_descricao, :class => 'form-control' %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-2 form-group">
    <%= form.label :receita, :class => 'control-label' %>
    <%= form.check_box :receita, id: :modalidade_receita %>
  </div>
  </div>

  <div class="row">
  <div class="col-lg-2 form-group">
    <%= form.label :despesa, :class => 'control-label' %>
    <%= form.check_box :despesa, id: :modalidade_despesa %>
  </div>
  </div>


  <div class="row">
  <div class="col-lg-7 form-group">  
      <input type="submit" name="commit" class="btn btn-primary" value="Salvar" data-disable-with="Salvar" />
      <%= link_to 'Voltar', modalidades_path, :class => "btn btn-primary"%>
  </div>
  </div>

  </div>

<% end %>

app/views/modalidades/edit.html.erb
<h1>Editar Modalidade</h1>

<%= render 'form', modalidade: @modalidade %>

app/views/modalidades/index.html.erb
 <div class="categdespesas index">
      <h2>Modalidades </h2>
       <%= form_tag modalidades_path( format:"html"), :method => 'get' do %>  
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
          

          <div class="col-lg-8">
          </div>
                  
        <div class="col-lg-2 form-group">  
          <span class="input-group-btn" style="display: inline-block;"><button class="btn btn-primary" type="button" onclick="javascript: location.href='<%= new_modalidade_path %>';"><i class="fa fa-plus-circle"></i> Nova Modalidade</button></span>
        </div>
        </div>
      </div>
      </div>
      <% end  %>  
      
  <div class="table-responsive">
  <table class="table table-hover table-striped" cellpadding="0" cellspacing="0">
      <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Receita</th>
      <th>Despesa</th>
      <th colspan="3"></th>
    </tr>
  </thead>
       <tbody>
    <% @modalidades.each do |modalidade| %>
      <tr>
        <td><%= modalidade.nome %></td>
        <td><%= modalidade.descricao %></td>
        <td><%= modalidade.receita ? 'Sim' : 'Não' %></td>
        <td><%= modalidade.despesa ? 'Sim' : 'Não' %></td>
        <td><%= link_to 'Exibir', modalidade %></td>
        <td><%= link_to 'Editar', edit_modalidade_path(modalidade) %></td>
        <td><%= link_to 'Deletar', modalidade, method: :delete, data: { confirm: 'Deseja Deletar Modalidade ' +modalidade.nome+'?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>


  </div>

app/views/modalidades/new.html.erb
<h1>Nova Modalidade</h1>

<%= render 'form', modalidade: @modalidade %>

app/views/modalidades/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <h2 class="page-header">
                Visualizar Modalidade
            </h2>
        </div>
    </div>
    <div class="curso form">

           <div class="row">

               <div class="col-lg-4 form-group">   
                  <label class = 'control-label'>Nome</label>
                  <input readonly="true" class = 'form-control' value="<%= @modalidade.nome %>" />
               </div>

           </div>    

           <div class="row">
                <div class="col-lg-4 form-group">   
                  <label class = 'control-label'>Referente</label>
                  <input readonly="true" class = 'form-control' value="<%= @modalidade.descricao %>" />
                </div>
           </div>

           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Receita</label>
                  <input readonly="true" class = 'form-control' value="<%= @modalidade.receita ? 'Sim' : 'Não' %>" />
                </div>
           </div>
                
           <div class="row">
                <div class="col-lg-2 form-group">  
                  <label class = 'control-label'>Despesa</label>
                  <input readonly="true" class = 'form-control' value="<%= @modalidade.despesa ? 'Sim' : 'Não' %>" />
                </div>
           </div>             
            
             <div class="row">
                <div class="col-lg-4 form-group">  
                  <%= link_to 'Editar', edit_modalidade_path(@modalidade), :class => "btn btn-primary" %>
                  <%= link_to 'Voltar', modalidades_path, :class => "btn btn-primary"%>
                </div>
            </div>
     
                          
    </div>
</div>